trigger:
  - main
pr: none
variables:
  - group: online-course-project-varible
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: Docker@2
    displayName: "Build Frontend Image"
    inputs:
      containerRegistry: 'acr_servis_baglantisi'
      repository: 'frontend-app'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      arguments: |
        --build-arg AUTH_TRUST_HOST=$(AUTH_TRUST_HOST)
        --build-arg NEXTAUTH_URL=$(NEXTAUTH_URL)
        --build-arg NEXT_PUBLIC_API_URL=$(NEXT_PUBLIC_API_URL)
        --build-arg NEXT_PUBLIC_ASSET_URL=$(NEXT_PUBLIC_ASSET_URL)
        --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$(NEXT_PUBLIC_GOOGLE_MAPS_API_KEY)
        
      tags: |
        latest

  - task: Docker@2
    displayName: "Push Frontend Image to ACR"
    inputs:
      containerRegistry: 'acr_servis_baglantisi'
      repository: 'frontend-app'
      command: 'push'
      tags: |
        latest

  - task: SSH@0
    displayName: "Deploy Frontend to VM"
    inputs:
      sshEndpoint: 'onlinecourse-vm-conn'
      runOptions: 'commands'
      commands: |
        docker login $(ACR_LOGIN_SERVER) -u $(ACR_NAME) -p $(ACR_PASSWORD) 2>/dev/null
        docker pull $(ACR_LOGIN_SERVER)/frontend-app:latest
        docker stop frontend-app 2>/dev/null || true
        docker rm frontend-app 2>/dev/null || true
        docker run -d --name frontend-app --restart always --network app-network -e NEXTAUTH_URL=$(NEXTAUTH_URL) -e AUTH_TRUST_HOST=$(AUTH_TRUST_HOST) -e NEXTAUTH_SECRET=$(NEXTAUTH_SECRET) -p 3000:3000 $(ACR_LOGIN_SERVER)/frontend-app:latest
        docker image prune -f
        docker ps | grep frontend-app
        docker logs frontend-app --tail 20